// CFブックのメーカー表記マスタ(現行VBA Shopserve用.bas:2035 Setメーカー名 の移植)
// 表記は VBA にハードコードされている値をそのまま持つ(iClass ごと×メーカーID)。
// "EE" は表に無く、シートのメーカー列の値を使う(iClass 2/8/16)。表に無いメーカーは VBA では Stop(停止)

const CF_MAKER_NAMES: Record<number, Record<string, string>> = {
  // 1: 日本語表記
  1: {
    I: "ファズー",
    A: "アグレッド",
    N: "NEC",
    O: "オーデリック",
    R: "オーブ",
    K: "コイズミ",
    W: "ライフオンプロダクツ",
    D: "ダイコー",
    Z: "タキズミ",
    L: "ダルトン",
    M: "東京メタル工業",
    T: "東芝",
    J: "日本電興",
    P: "パナソニック",
    H: "ハモサ",
    PH: "ファイテン",
    MA: "マントラ",
    E: "三菱電機",
    X: "BRID[メルクロス]",
    Y: "ユーワ",
    IM: "ミンカエアー",
  },
  // 2: 英語＋(日本語)
  2: {
    I: "FAZOO(ファズー)",
    A: "AGLED(アグレッド)旧丸善電機(Lucky)",
    N: "NEC_LIGHTING(NECライティング)",
    O: "ODELIC(オーデリック)",
    R: "ORRB(オーブ)",
    K: "KOIZUMI(コイズミ)",
    W: "Life on Products(ライフオンプロダクツ)",
    D: "DAIKO(ダイコー)",
    Z: "タキズミ(瀧住電機工業)",
    L: "DULTON(ダルトン)",
    M: "TOKYOMETAL(東京メタル工業)",
    T: "TOSHIBA(東芝ライテック)",
    J: "NIHON DENKO(日本電興)",
    P: "Panasonic(パナソニック)",
    H: "HERMOSA(ハモサ)",
    PH: "Phiten(ファイテン)",
    MA: "mAntra(マントラ)",
    E: "MITSUBISHI ELECTRIC(三菱電機)",
    X: "BRID(ブリッド)",
    Y: "YOUWA(ユーワ)",
    IM: "MinkaAire(ミンカエアー)",
    "-": "その他",
  },
  // 3: カテゴリ専用
  3: {
    I: "アイ・ヴィレッジ／I.Village",
    A: "アグレッド／AGLED",
    N: "NEC",
    O: "オーデリック／ODELIC",
    R: "オーブ／ORRB",
    K: "コイズミ照明／KOIZUMI",
    W: "Life on Products／ライフオンプロダクツ",
    D: "大光電機／DAIKO",
    Z: "タキズミ／TAKIZUMI",
    L: "ダルトン／DULTON",
    M: "東京メタル工業／Tome",
    T: "東芝／TOSHIBA",
    J: "日本電興／NIHON DENKO",
    P: "パナソニック／Panasonic",
    H: "ハモサ／HERMOSA",
    PH: "ファイテン／phiten",
    MA: "マントラ／mAntra",
    E: "三菱電機／MITSUBISHI",
    X: "メルクロス／BRID",
    Y: "ユーワ／YOUWA",
    IM: "海外／輸入ファン",
  },
  // 4: 画像カテゴリ(フォルダ名)
  4: {
    I: "ivillage",
    A: "agled",
    N: "nec",
    O: "odelic",
    R: "orrb",
    K: "koizumi",
    W: "LifeOnProducts",
    D: "daiko",
    Z: "takizumi",
    L: "dulton",
    M: "tokyometal",
    T: "toshiba",
    J: "nihondenko",
    P: "panasonic",
    H: "hermosa",
    PH: "phiten",
    MA: "mantra",
    E: "mitsubishi",
    X: "mercros",
    Y: "youwa",
    IM: "minka-aire",
    EE: "etc",
  },
  // 5: 隠しキーワード用
  5: {
    I: ";MIV",
    A: ";MA",
    N: ";MN",
    O: ";MO",
    R: ";MR",
    K: ";MK",
    W: ";MW",
    D: ";MD",
    Z: ";MZ",
    L: ";ML",
    M: ";MM",
    T: ";MT",
    J: ";MJ",
    P: ";MP",
    H: ";MH",
    PH: ";MPH",
    MA: ";MMA",
    E: ";ME",
    X: ";MX",
    Y: ";MY",
    IM: ";MIM",
  },
  // 6: 英語表記
  6: {
    I: "I.VILLAGE",
    A: "AGLED",
    N: "NEC_LIGHTING",
    O: "ODELIC",
    R: "ORRB",
    K: "KOIZUMI",
    W: "LIFE ON PRODUCTS",
    D: "DAIKO",
    Z: "TAKIZUMI",
    L: "DULTON",
    M: "TOKYOMETAL",
    T: "TOSHIBA",
    J: "NIHONDENKO",
    P: "PANASONIC",
    H: "HERMOSA",
    PH: "PHITEN",
    MA: "MANTRA",
    E: "MITSUBISHI ELECTRIC",
    X: "BRID MERCROS",
    Y: "YOUWA",
    IM: "MINKA AIRE",
  },
  // 7: ブランド名
  7: {
    I: "fazoo（ファズー）",
    A: "アグレッド",
    N: "NEC",
    O: "オーデリック",
    R: "オーブ",
    K: "コイズミ",
    W: "ライフオンプロダクツ",
    D: "DAIKO (大光電機）",
    Z: "タキズミ",
    L: "ダルトン",
    M: "東京メタル工業",
    T: "東芝",
    J: "日本電興",
    P: "パナソニック",
    H: "ハモサ",
    PH: "ファイテン",
    MA: "マントラ",
    E: "三菱電機",
    X: "メルクロス",
    Y: "ユーワ",
    IM: "ミンカエアー",
  },
  // 8: FS用ディスクリプション用
  8: {
    I: "ファズー／fazoo製",
    A: "アグレッド／AGLED製",
    N: "NEC製",
    O: "オーデリック／ODELIC製",
    R: "オーブ／ORRB製",
    K: "コイズミ照明／KOIZUMI製",
    W: "ライフオンプロダクツ／Life on Products製",
    D: "大光電機／DAIKO製",
    Z: "瀧住電機工業／TAKIZUMI製",
    L: "ダルトン／DULTON製",
    M: "東京メタル工業／Tome製",
    T: "東芝／TOSHIBA製",
    J: "日本電興／NIHON DENKO製",
    P: "パナソニック／Panasonic製",
    H: "ハモサ／HERMOSA製",
    PH: "ファイテン／PHITEN製",
    MA: "マントラ／MANTRA製",
    E: "三菱電機／MITSUBISHI製",
    X: "メルクロス／BRID製",
    Y: "ユーワ／YOUWA製",
    IM: "海外／輸入",
  },
  // 9: FS用(旧メイングループ)
  9: {
    I: "アイ・ヴィレッジ／I.Village",
    A: "アグレッド／AGLED",
    N: "NEC",
    O: "オーデリック／ODELIC",
    R: "オーブ／ORRB",
    K: "コイズミ照明／KOIZUMI",
    W: "ライフオンプロダクツ／Life on Products",
    D: "大光電機／DAIKO",
    Z: "瀧住電機工業／TAKIZUMI",
    L: "ダルトン／DULTON",
    M: "東京メタル工業／Tome",
    T: "東芝／TOSHIBA",
    J: "日本電興／NIHON DENKO",
    P: "パナソニック／Panasonic",
    H: "ハモサ／HERMOSA",
    PH: "ファイテン／Phiten",
    MA: "マントラ／mAntra",
    E: "三菱電機／MITSUBISHI",
    X: "メルクロス／BRID",
    Y: "ユーワ／YOUWA",
    IM: "海外／輸入ファン",
  },
  // 10: FS用カテゴリ用/グループ用
  10: {
    I: "ファズーファン／FAZOO FAN",
    A: "アグレッド／AGLED",
    N: "NEC",
    O: "オーデリック／ODELIC",
    R: "オーブ／ORRB",
    K: "コイズミ照明／KOIZUMI",
    W: "JAVALO ELF／ライフオンプロダクツ",
    D: "大光電機／DAIKO",
    Z: "瀧住電機工業／TAKIZUMI",
    L: "ダルトン／DULTON",
    M: "東京メタル工業／Tome",
    T: "東芝／TOSHIBA",
    J: "日本電興／NIHON DENKO",
    P: "パナソニック／Panasonic",
    H: "ハモサ／HERMOSA",
    PH: "ファイテン／phiten",
    MA: "マントラ／mAntra",
    E: "三菱電機／MITSUBISHI",
    X: "メルクロス／BRID",
    Y: "ユーワ／YOUWA",
    IM: "海外／輸入ファン",
  },
  // 11: FS用商品URL用
  11: {
    I: "//www.fazoo.biz/c/ivillage/",
    A: "//www.fazoo.biz/c/agled/",
    N: "//www.fazoo.biz/c/nec/",
    O: "//www.fazoo.biz/c/odelic/",
    R: "//www.fazoo.biz/c/orrb/",
    K: "//www.fazoo.biz/c/koizumi/",
    W: "//www.fazoo.biz/c/javalo-elf/",
    D: "//www.fazoo.biz/c/daiko/",
    Z: "//www.fazoo.biz/c/takizumi/",
    L: "//www.fazoo.biz/c/dulton/",
    M: "//www.fazoo.biz/c/tome/",
    T: "//www.fazoo.biz/c/toshiba/",
    J: "//www.fazoo.biz/c/nihon-denko/",
    P: "//www.fazoo.biz/c/panasonic/",
    H: "//www.fazoo.biz/c/hermosa/",
    PH: "//www.fazoo.biz/c/phiten/",
    MA: "//www.fazoo.biz/c/mantra/",
    E: "//www.fazoo.biz/c/mitsubishi/",
    X: "//www.fazoo.biz/c/brid/",
    Y: "//www.fazoo.biz/c/youwa/",
    IM: "//www.fazoo.biz/c/import/",
    EE: "//www.fazoo.biz/c/option/",
  },
  // 12: メーカーimg表示用(ファイル名" alt="…)
  12: {
    I: "ivillage_logo.png\" alt=\"シーリングファンライト通販専門店ファズー fazoo",
    A: "agled_logo.gif\" alt=\"アグレッドのメーカーロゴ",
    N: "nec_logo.gif\" alt=\"NECのメーカーロゴ",
    O: "odelic_logo.gif\" alt=\"オーデリックのメーカーロゴ",
    R: "orrb_logo.gif\" alt=\"オーブのメーカーロゴ",
    K: "koizumi_logo.gif\" alt=\"コイズミのメーカーロゴ",
    W: "lop_logo.gif\" alt=\"ライフオンプロダクツのメーカーロゴ",
    D: "daiko_logo.gif\" alt=\"ダイコーのメーカーロゴ",
    Z: "takizumi_logo.gif\" alt=\"タキズミのメーカーロゴ",
    L: "dulton_logo.gif\" alt=\"DULTONのメーカーロゴ",
    M: "tokyometal_logo.gif\" alt=\"東京メタルのメーカーロゴ",
    T: "toshiba_logo.gif\" alt=\"東芝のメーカーロゴ",
    J: "nihondenko_logo.gif\" alt=\"日本電興のメーカーロゴ",
    P: "panasonic_logo.gif\" alt=\"パナソニックのメーカーロゴ",
    H: "hermosa_logo.gif\" alt=\"HERMOSAのメーカーロゴ",
    PH: "phiten_logo.gif\" alt=\"ファイテンのメーカーロゴ",
    MA: "mantra_logo.gif\" alt=\"マントラのメーカーロゴ",
    E: "mitsubishi_logo.gif\" alt=\"三菱電機のメーカーロゴ",
    X: "mercros_logo.gif\" alt=\"メルクロスのメーカーロゴ",
    Y: "youwa_logo.gif\" alt=\"ユーワのメーカーロゴ",
    IM: "minka-aire_logo.gif\" alt=\"Minka Aireのメーカーロゴ",
  },
  // 13: Yahoo用カテゴリ用
  13: {
    I: "ファズーオリジナル／fazoo original",
    A: "アグレッド",
    N: "NEC",
    O: "オーデリック／ODELIC",
    R: "オーブ／ORRB",
    K: "コイズミ照明／KOIZUMI",
    D: "大光電機／DAIKO",
    Z: "TAKIZUMI",
    L: "ダルトン／DULTON",
    M: "東京メタル工業／TOME",
    T: "東芝",
    J: "日本電興／NIHON DENKO",
    P: "パナソニック／Panasonic",
    H: "ハモサ／HERMOSA",
    PH: "ファイテン／Phiten",
    MA: "マントラ／mAntra",
    W: "JAVALO ELF／ライフオンプロダクツ",
    E: "三菱電機／MITSUBISHI",
    X: "メルクロス／BRID",
    Y: "ユーワ／YOUWA",
    IM: "輸入／海外ファン",
  },
  // 14: Yahoo用ブランドコード用
  14: {
    I: "",
    A: "",
    N: "52",
    O: "491",
    R: "",
    K: "741",
    W: "",
    D: "4251",
    Z: "40135",
    L: "1155",
    M: "37556",
    T: "2352",
    J: "",
    P: "1460",
    H: "15038",
    PH: "",
    MA: "",
    E: "",
    X: "",
    Y: "18568",
    IM: "",
  },
  // 15: FS用メーカーimg width/height
  15: {
    I: "width=\"176\" height=\"56\"",
    A: "width=\"136\" height=\"30\"",
    N: "width=\"108\" height=\"36\"",
    O: "width=\"150\" height=\"36\"",
    R: "width=\"60\" height=\"70\"",
    K: "width=\"216\" height=\"36\"",
    W: "width=\"64\" height=\"70\"",
    D: "width=\"136\" height=\"36\"",
    Z: "width=\"208\" height=\"36\"",
    L: "width=\"176\" height=\"36\"",
    M: "width=\"256\" height=\"36\"",
    T: "width=\"204\" height=\"36\"",
    J: "width=\"358\" height=\"36\"",
    P: "width=\"208\" height=\"36\"",
    H: "width=\"154\" height=\"36\"",
    PH: "width=\"208\" height=\"36\"",
    MA: "width=\"160\" height=\"48\"",
    E: "width=\"116\" height=\"48\"",
    X: "width=\"104\" height=\"36\"",
    Y: "width=\"150\" height=\"36\"",
    IM: "width=\"148\" height=\"48\"",
  },
  // 16: FS用検索キーワード(末尾カンマ付き)
  16: {
    I: "I.Village,IV,アイ・ヴィレッジ,アイヴィレッジ,fazoo,ファズーファン,",
    A: "AGLED,アグレッド,丸善電機,Lucky,",
    N: "NEC,NECライティング,",
    O: "ODELIC,オーデリック,",
    R: "ORRB,オーブ,",
    K: "KOIZUMI,コイズミ,",
    W: "HANWA,阪和,",
    D: "DAIKO,ダイコー,",
    Z: "タキズミ,瀧住電機工業,",
    L: "DULTON,ダルトン,",
    M: "東京メタル工業,",
    T: "TOSHIBA,東芝ライテック,",
    J: "NIHON DENKO,日本電興,",
    P: "Panasonic,パナソニック,",
    Y: "YOUWA,ユーワ,",
    X: "MERCROS,メルクロス,",
    H: "HERMOSA,ハモサ,",
    PH: "PHITEN,ファイテン,",
    MA: "MANTRA,マントラ,",
    E: "MITSUBISHI ELECTRIC,三菱電機,",
    IM: "Minka Aire,ミンカエアー,",
    "-": "",
  },
};

// makerCellName: シートのメーカー列(INPUT_COLメーカー)の値。EE(その他メーカー)の表記に使う
export function cfMakerName(makerCode: string | null | undefined, iClass: number, makerCellName?: string | null): string {
  const code = makerCode ?? "";
  if (code === "EE") {
    const cell = makerCellName ?? "";
    if (iClass === 2 || iClass === 8) return cell;
    if (iClass === 16) return `${cell},`;
  }
  return CF_MAKER_NAMES[iClass]?.[code] ?? "";
}
