// futureshop 商品CSV(FS_ccGoods)の111列定義
// 列名・順序は現行Excelの出力シート FS_ccGoods ヘッダー行から抽出した実物
// (documents/01_調査/01_全体/04_現行VBA仕様_CSV出力.md §4.1 / 値の根拠は同シートの実出力行)。
// source_expr: const:固定値 / func:変換関数(routes/exports.ts) / 属性参照。空文字は const: のみ。
// 未実装の重い生成列(独自コメント等)は func:fs_todo(空を返す)にして並行出力比較で差分として検出させる。


export const FS_CCGOODS_COLUMNS: Array<[string, string]> = [
  ["コントロールカラム", "func:fs_control"],
  ["商品URLコード", "product.productCode"],
  ["ステータス", "func:fs_status"], // CF=空 / PL=0固定
  ["商品番号", "product.productCode"],
  ["商品名", "func:fs_product_name"],
  ["メイングループ", "func:fs_main_group"],
  ["優先度", "func:fs_sort_priority"],
  ["本体価格", "func:fs_sales_price"],
  ["定価", "func:fs_list_price"],
  ["消費税", "func:fs_tax_setting"],
  ["販売期間(From)", "func:fs_sale_from"], // CF=2012052000:00固定 / PL=空
  ["販売期間(to)", "func:fs_sale_to"],
  ["販売期間表示", "const:1"],
  ["クール便指定", "func:fs_cool_flag"], // CF=空 / PL=0
  ["送料", "const:0"],
  ["送料パターン", "func:fs_postage_pattern"],
  ["送料パターン表示", "const:0"],
  ["送料個別金額", "const:"],
  ["個別送料表示", "func:fs_pl_zero"], // PL=0 / CF=空
  ["オススメ商品商品ページ内表示", "func:fs_recommend_flag"], // PL=0 / CF=関連商品あり→1
  ["オススメ商品リスト", "func:fs_recommend_list"], // CF=関連商品(コード列挙)
  ["オススメ商品表示方法", "func:fs_recommend_flag"],
  ["商品価格上部コメントHTMLタグ", "func:fs_pl_zero"],
  ["商品価格上部コメント", "const:"],
  ["定価価格前文字", "const:定価"],
  ["定価価格後文字", "const:のところ"],
  ["販売価格前文字", "const:当店特別価格"],
  ["取消線", "func:fs_strike"], // CF=オープン価格は0 / PL=1
  ["定価表示方法", "func:fs_pl_zero"],
  ["在庫管理", "func:fs_stock_control"],
  ["在庫数表示設定", "func:fs_pl_zero"],
  ["在庫数表示設定方法", "func:fs_pl_zero"],
  ["在庫僅少表示閾値", "const:"],
  ["在庫なし表示テキスト", "const:"],
  ["在庫なし表示テキスト表示方法", "func:fs_pl_zero"],
  ["現在在庫数", "func:fs_current_stock"], // PLのみモードで0/1000。CF=空
  ["調整在庫数", "const:"],
  ["在庫数切れメール閾値", "const:"],
  ["バリエーション横軸名", "const:"],
  ["バリエーション縦軸名", "func:fs_variation_axis"], // CF=バリエーション1項目名
  ["会員価格設定", "func:fs_pl_zero"],
  ["会員価格", "const:"],
  ["アクセス制限", "func:fs_pl_zero"],
  ["ポイント付与率設定", "func:fs_pl_zero"],
  ["ポイント付与率", "func:fs_pl_zero"],
  ["ステータス（他社サービス）", "func:fs_other_service_status"],
  ["サンプル商品設定", "const:"],
  ["サンプル商品同梱設定", "const:"],
  ["最大購入制限個数", "const:"],
  ["入荷お知らせメールボタン表示", "const:"],
  ["JANコード", "func:fs_jan_wide"],
  ["キャッチコピー", "const:"],
  ["レコメンド２：行動履歴収集タグ出力フラグ", "const:"],
  ["レコメンド２：レコメンド商品出力フラグ", "const:"],
  ["レコメンド２：レコメンド表示フラグ", "const:"],
  ["レコメンド２：レコメンド使用タグ優先設定", "const:"],
  ["レコメンド２：商品ページ上部コメントの上", "const:"],
  ["レコメンド２：商品ページ上部コメントの下", "const:"],
  ["レコメンド２：商品ページ下部コメントの上", "const:"],
  ["レコメンド２：商品ページ下部コメントの下", "const:"],
  ["レコメンド２：商品ページおすすめ商品の上", "const:"],
  ["レコメンド２：商品ページおすすめ商品の下", "const:"],
  ["お気に入り登録数", "const:"],
  ["メール便指定", "const:"],
  ["メール便同梱数", "const:"],
  ["バンドル販売", "const:"],
  ["外部連携任意項目", "func:fs_catch_copy"],
  ["おすすめ商品表示パターン設定", "const:"],
  ["おすすめ商品表示パターン(コマースクリエイター)", "const:"],
  ["外部連携商品名", "const:"],
  ["外部連携商品説明", "const:"],
  ["レイアウト割当名", "func:fs_layout_name"], // PLのみ値あり。CF=空
  ["ページ名(コマースクリエイター)", "func:fs_page_name"],
  ["ページ名表示方法(コマースクリエイター)", "const:2"],
  ["キーワード(コマースクリエイター)", "func:fs_keywords"],
  ["キーワード表示方法(コマースクリエイター)", "const:2"],
  ["Description(コマースクリエイター)", "func:fs_description"],
  ["Description表示方法(コマースクリエイター)", "const:2"],
  ["商品一言説明(コマースクリエイター)", "const:"],
  ["商品説明（大）", "func:fs_description_large"],
  ["商品説明（小）", "const:"],
  ["独自コメント（1）", "func:fs_comment_1"],
  ["独自コメント（2）", "func:fs_comment_2"],
  ["独自コメント（3）", "func:fs_comment_3"],
  ["独自コメント（4）", "func:fs_comment_4"],
  ["独自コメント（5）", "func:fs_comment_5"],
  ["独自コメント（6）", "func:fs_comment_6"],
  ["独自コメント（7）", "func:fs_comment_7"],
  ["独自コメント（8）", "func:fs_comment_8"],
  ["独自コメント（9）", "func:fs_comment_9"],
  ["独自コメント（10）", "func:fs_comment_10"],
  ["独自コメント（11）", "func:fs_comment_11"],
  ["独自コメント（12）", "func:fs_comment_12"],
  ["独自コメント（13）", "func:fs_comment_13"],
  ["独自コメント（14）", "func:fs_comment_14"],
  ["独自コメント（15）", "func:fs_comment_15"],
  ["独自コメント（16）", "func:fs_comment_16"],
  ["独自コメント（17）", "func:fs_comment_17"],
  ["独自コメント（18）", "func:fs_comment_18"],
  ["独自コメント（19）", "func:fs_comment_19"],
  ["独自コメント（20）", "func:fs_comment_20"],
  ["レコメンド２：レコメンド表示フラグ(コマースクリエイター)", "const:"],
  ["レコメンド２：レコメンド使用タグ優先設定(コマースクリエイター)", "const:"],
  ["レコメンド２：出力タグ１", "const:"],
  ["レコメンド２：出力タグ２", "const:"],
  ["レコメンド２：出力タグ３", "const:"],
  ["レコメンド２：出力タグ４", "const:"],
  ["レコメンド２：出力タグ５", "const:"],
  ["レコメンド２：出力タグ６", "const:"],
  ["商品URL", "const:"], // PL版レイアウトの112列目相当(常に空)。CF版シートには無い列
  ["登録日時", "const:"],
  ["最終更新日時", "const:"], // 現行VBAはoff-by-oneで最終列を書かない(常に空)
];
